### ISSUE TITLE
No apparent way to keep confluence.cfg.xml out of the container

### ISSUE THREAD

**Issue by mccartney** [cptactionhank/docker-atlassian-confluence#22]
I believe it would be great if the Docker image was ready for keeping `confluence.cfg.xml` outside of the container. As Docker supports mapping directories (not files), it seems not so easy right now. And the file is likely to be edited as it contains critical configuration - e.g. database connection parameters.

I might not understand something, as I am new to Docker, but the only way I found to configure `confluence.cfg.xml` was to edit it within the container (e.g. with `docker cp` or similar).

**Comment by cptactionhank** [comment]
Can you elaborate a bit more on this?

The `confluence.cfg.xml` is located in the root of the Confluence home folder and it is marked as a volume in the `Dockerfile` which means that the volume is guaranteed to be persisted between container restarts. So when needed you can modify the XML file and be sure that the changes persist throughout the life of the container. You could mount another folder on top of the Home folder ie. `/var/atlassian/confluence` to use a custom location of your choosing, I for example on my home server have mounted to homefolder to `/srv/atlassian/confluence`. But this is not necessary for utilising Confluence or customisations, it is just matches my specific use case on my home server.

**Comment by cptactionhank** [comment]
Since the home folder is marked a volume by the Docker Image the changes in this folder is persisted between container restarts. This means you can modify the file and be sure the changes are kept and to do this you could utilise `docker cp` to copy back and forth or use `docker exec` to modify directly from the shell.

You could also have mounted an external folder on the host inside the container in the home directory and from this way have a persisted home folder that can easily be modified through the tools on the host.

**Comment by mccartney** [comment]
Thanks for the tip. You are right.

Actually - what I ended up doing was keeping the whole `$CONFLUENCE_HOME` as a mapped volume (docker run -v ...). Not only the single `confluence.cfg.xml` file.
