### ISSUE TITLE
Upgrade confluence with docker containers

### ISSUE THREAD

**Issue by nickvth** [cptactionhank/docker-atlassian-confluence#24]
How to upgrade between versions?

**Comment by cptactionhank** [comment]
Due to my employer I can't really help you with this directly other than to encourage you to either seek out documentation about Confluence and about Docker or to seek professional help from Atlassian experts, like my employer Translucent.

Here are some resources found using Google:
* https://confluence.atlassian.com/doc/upgrading-confluence-4578.html
* https://docs.docker.com/engine/reference/run/
