### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by beevelop** [cptactionhank/docker-atlassian-confluence#26]
As GitHub offers a seamless way to automatically track releases via RSS-Feed, it would be great to have the respective commits tagged.

Edit: e.g. 5370ad9e1d6179eb5812a6fc4a7316577d742930 or 7b687d1956219816cb6a7c1cdc5bca39e6f091a2

**Comment by cptactionhank** [comment]
I'll try an look into to this, do you have a use case for this?

**Comment by beevelop** [comment]
My personal use case is an IFTTT automation that grabs the release feed from GitHub and creates an issue in my „infrastructure”-related repositories as soon as a new release is available. This way I can keep track of every new release and make sure my deployment files (e.g. for Docker-Compose or Kubernetes) are up-to-date.

Additionally I'd like to push this workflow even further by automatically applying the new version to an *upgrade* branch, which gets deployed to a staging environment and runs some predefined tests to verify there were no breaking changes in the latest release.

**Comment by cptactionhank** [comment]
Sounds very interesting and I would like to know more details about your setup on how you perform the various tasks 👍 

I'm contemplating on how to handle this and it seems like Git (or my knowledge) does not handle branches and tags with the exact same name very well. It looks like to be either tags or branches and for my automated building setup and ability to update critical updates to previous versions there's a strong need for version branches and which I'd want to keep as is.

So left is the expectation to tag format; GitHub's user interface and descriptions seems to recommend the style of `v#.#.#` and as such we could create tags like `v5.10.0` and `v5.10.1`. How would this fit in your automated architecture system, would it be able to handle this? Because I for now firmly believe the method of application version branches should be kept as is.

**Comment by cptactionhank** [comment]
Another thought I just had: Isn't it kinda the wrong place to look for a new version of the Atlassian Confluence image instead of looking at the Docker Hub. 

Now I know that the Docker Hub does not have RSS feeds but it should be the true place to look for new image versions or updated image ie. image hash. For instance the scenario when the underlying `java` image is updated/security patched then the various Atlassian images will be rebuilt to use the newer Java base image and get re-tagged. This case would not be detectable relying on the source code of the higher level container image, which would be just as important if not more in a context of automatic upgrading/updating the application container.

**Comment by beevelop** [comment]
`v#.#.#` tags are IMHO fine. Even though they do not match how Docker's official images are tagged, I personally think this is the best way to stay consistent with GitHub's best practices. I use this style for all my automated builds too.

Alternatively I think @sameersbn's way of tagging e.g. his [GitLab image](https://github.com/sameersbn/docker-gitlab/releases) is quite solid too. He increments a suffix for changes to the same version (e.g. `8.9.6-1`).

I do agree that – for my (and probably most) use cases – getting the version straight from Docker Hub would be the best solution to keep the versions up-to-date. Nonetheless I think it might be useful to have the underlying source files versioned too, considering use cases involving private registries, „manual” builds or any kind of *isolated environments*.

**Comment by cptactionhank** [comment]
My Atlassian and Sameersbn's GitLab images are not setup in the exact same way, the methods they have their different pro's and con's and after some further thought I do not believe tagging is a good suitable solution for my build/release methods.

For you I have found that RSS ATOM feed about changes `https://github.com/cptactionhank/docker-atlassian-confluence/commits/master.atom` you could rely on as well. For example you can get a commit feed to notice changes and by following `master` branch you can ensure you are always up-to-date with the newest version. Another possibility is to follow a version-branch to make sure you get the latest security update or other modification eg. `https://github.com/cptactionhank/docker-atlassian-jira/commits/5.10.2.atom`

These should ATOM feeds should be sufficient for you to continue your work but still have the consequence that you will not have the exactly newest version of the application image, but you will have the latest version with the latest modifications from my end. So the underlying updates ie. security updates for Java or images further up the chain will not be discovered since relying on GitHub rather than the Docker Hub.

Happy hacking.
