### ISSUE TITLE
Future of this image

### ISSUE THREAD

**Issue by xeor** [cptactionhank/docker-atlassian-confluence#28]
I noticed that Atlassian have finally gotten on the wagon and is now providing an official docker image of confluence (and probably other products).

I'm not sure if you have anything to do with this, but they have [obviously](https://bitbucket.org/atlassian/docker-atlassian-confluence-server/src/8d664e51d6564d20ffec13d4f385fa9a520bafb9/Dockerfile?at=master&fileviewer=file-view-default) gotten almost everything from this repository.

What will be the future of this repo/image?

**Comment by cptactionhank** [comment]
Hi @xeor, thank you for the question. Interesting source ;) and cool to see Confluence finally is on the wagon as well. 

Since Atlassian has been so long to really get on board and that usage of my images continues to grow my immediate plans are to continue providing new versions of the images. I have a nice little setup to provide a basic image of the software which should cover most users need, with automated building, testing, and version releases so I should still be able to provide updated versions as soon as Atlassian.

**Comment by xeor** [comment]
I definitively though you where involved.. In that case; congrats in such a quality on the job that the vendor ended up duplicating it 👍 

Thanks for the update tho, and thanks again for doing this!

Maybe Atlassian should outsource this job to you and let you do this official for them.... :=)

**Comment by cptactionhank** [comment]
Thank you :)
