### ISSUE TITLE
"OpenJDK Runtime Environment is not a supported Java distribution."

### ISSUE THREAD

**Issue by mccartney** [cptactionhank/docker-atlassian-confluence#29]
# Steps to reproduce:
1. Run the 5.10.4 (currently latest) Confluence
2. In the admin section navigate to [http://$ip:$port/plugins/servlet/stp/view/?tab=detect-issues]

# Observed
```
Confluence complains about the JDK version:
Problems Detected Error
Supported Platforms Error
Java Version and Vendor
What does this check do?
Checks if your JDK / JRE version and vendor are supported.
Result
OpenJDK Runtime Environment is not a supported Java distribution.
```

**Comment by mccartney** [comment]
Probably it [has licensing obstacles](http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/) and I am not sure if this is possible at all to package a Docker container with a JDK which [Atlassian considers as supported](https://confluence.atlassian.com/doc/supported-platforms-207488198.html) ("Oracle JRE / JDK").

**Comment by cptactionhank** [comment]
Thank you for raising this issue and you're right, it is indeed because of licensing issues. I believe that Oracle or Docker is rather aggressive about this, which is why it's not easy to find Oracle Java images. Atlassians official images uses OpenJDK as well and it's rather dumb that Java should be platform agnostic but Atlassian do not support other than Oracle. I have not had any reports or experienced for myself executing Conflunce on OpenJDK.

Perhaps this could be documented better but for now and the near feature this image will continue to use an unsupported Java platform. Feel free to request OpenJDK support for Confluence at Atlassian as they already support it for some of their other products.

**Comment by mccartney** [comment]
That makes sense. I am the most concerned of the big fat warning being displayed in the admin panel.

**Comment by mccartney** [comment]
For reference, the [official documentation for Confluence](https://confluence.atlassian.com/confkb/is-openjdk-supported-by-confluence-297667642.html) mentions:

>   A number of problems can occur when using OpenJDK, as Confluence's internal code as well as third party plugins assume you are using a supported JDK.

... which is a vague statement. I read it more like "we don't know if it works" rather than "we know it doesn't". They don't point to any specific description of real problems when running on OpenJDK.

Let's vote for [CONF-16431 "Officially Support openJDK"](https://jira.atlassian.com/browse/CONF-16431)

**Comment by dinhluong92** [comment]
How about this.
 https://github.com/oracle/docker-images/tree/master/OracleJava

**Comment by stefan-wegener** [comment]
In case anyone is still getting here: Confluence is now providing a guide how to modify their Dockerfile to get Oracle Java running inside of it (https://confluence.atlassian.com/confkb/update-the-confluence-docker-image-to-use-oracle-jdk-829062521.html). It think the steps mentioned there could also be applicable to the Dockerfile of this project.
