### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by vytautasgimbutas** [cptactionhank/docker-atlassian-confluence#51]
Hello,
do you have strategy for performing upgrades? I tried upgrading from 5.9.x to 6.2.x just by spinning up new version docker container, but it failed.

**Comment by cptactionhank** [comment]
Hello,

Due to my employee relationship I cannot support you in upgrading you're Confluence instance, since it is something my workplace does professionally.

I can however urge you to read the administrative and installation documentation which Atlassian provide where you can se how to upgrade Confluence and special instructions upgrading to the next version increment.

If others has something to recommend they're more than welcome.
