### ISSUE TITLE
Collaborative editing does not work sometimes

### ISSUE THREAD

**Issue by gorilych** [cptactionhank/docker-atlassian-confluence#60]
Similar to https://confluence.atlassian.com/confkb/editor-fails-to-load-in-confluence-6-x-due-to-could-not-initialize-class-org-xerial-snappy-snappy-error-859462192.html

But the reason is not in noexec /tmp, of course. Problem is in missing libc.so.6:

bash-4.4$ ldd /tmp/snappy-1.1.0.1-122fad6e-78ac-4f47-b751-2591e091c9f8-libsnappyjava.so
... Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory ..

This can be fixed by adding libc6-compat into docker image (tested this on a running container)

**Comment by kreischweide** [comment]
Can confirm, fixed a strange problem that

`/synchrony/v1/data/Synchrony-...`

routes always responded with 404 code and "missing token" body. Since adding this to the image, those two errors are gone if the editor is loaded.

**Comment by majochi** [comment]
Same here. Added another glibc compat alternative and its working now.

```
FROM cptactionhank/atlassian-confluence:6.7.1

USER root

# workaround for running native lib /tmp/snappy-1.1.0.1-327f818c-0e3b-40a0-85f0-2c773e1e7fac-libsnappyjava.so
# see https://github.com/xerial/snappy-java
RUN set -ex \
    && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub \
    && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk \
    && apk add --no-cache glibc-2.27-r0.apk \
    && rm glibc-2.27-r0.apk

USER daemon
```

**Comment by martin-gerdes** [comment]
Thank you!
We had the same problem: Certain sites could not be edited. Interestingly even though collaborative editing was disabled!
Additionally jira links would not display correctly.
Anyway, we had the same error messages, so I tried the fix, and after a restart both issues have now been resolved.

In light of the fact that cptactionhank offers both confluence and jira docker instances, it would be great if that fix could be integrated into the build!

**Comment by cptactionhank** [comment]
Should be fixed now, branches based on Alpine are updated. Please pull the new version and create your containers again.

**Comment by inash** [comment]
Hi, I had to additionally add **gcompat** package to make it work with the recent 6.14.1 image.

**Comment by martin-gerdes** [comment]
Thank you very very much, @inash !
Your comment absoulutely saved my day.
I first thought that removing my old workaround would be enough, after all, the solution to this problem should be now incorporated into the regular docker image, right?

Well no, the problem was back, and I assume affects every single user of the image (or at least everybody with an application link to jira)! (certain confluence sites can not be edited, links to jira do not render in page).

running "apk add gcompat" in the container and then restarting it fixed both problems.

Again, I would suggest adding that to the docker image so that such obscure fixes are not needed!(though admittedly installing a package through the package management system is at least cleaner than hardcoding using wget to fetch a specific version of glibc ...)

**Comment by dsteinkopf** [comment]
Nice! This also helped in my case. I've just pushed my update to my repo https://github.com/dsteinkopf/confluence-dup and docker hub https://cloud.docker.com/repository/docker/dsteinkopf/confluence-dup - if anyone might find this helpful here.

**Comment by ampedandwired** [comment]
gcompat seems to have been added to the latest image in #79
